version: "3.9"

services:
  style_shop:
    network_mode: "host"        
    build: 
      context: ./
      dockerfile: ./Dockerfile
    image: yingshaoxo/play_with_css
    environment:
      - ADMIN_EMAIL=yingshaoxo@gmail.com
    volumes:
      - "./dist:/root/html/play-with-css"
    restart: unless-stopped